[package]
name = "leptos_jkinsight_nl"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = "0.3.1"
leptos_router = { version = "0.3.1", features = ["csr"] } 
